"""Añadir tabla de productos e imagen

Revision ID: af9a818d5baf
Revises: 35965f67318f
Create Date: 2024-06-10 16:00:12.552838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9a818d5baf'
down_revision = '35965f67318f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('descripcion', sa.String(length=5000), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    op.drop_table('productos')
    # ### end Alembic commands ###
